<a href="https://colab.research.google.com/github/ClydeMic/A.I.SearchAlgorithms/blob/master/Feature_Selection_%26_Regression_using_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import libraries.

- Pandas : used for reading from the .csv file
- Numpy : used for mathematical computations e.g converting arr to numpy arr
- Sklearn : 
- Keras : 
- Matplotlib : used to plot and visualize  

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC
from sklearn.feature_selection import SelectFromModel
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import Adam
import matplotlib.pyplot as plt
from sklearn import metrics

In [ ]:
data = pd.read_csv('/content/Housing Pricing.csv')

In [ ]:
# size of the dataset
data.shape

(1460, 77)

In [ ]:
# get the first five rows of the dataset
data.head()

Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 77 columns]

In [ ]:
original_features=list(data.columns)
original_features

In [ ]:
# remove the id column (starts from 1)
data.drop('Id',inplace=True,axis=1)
data.head(1)

MSSubClass MSZoning  LotFrontage  ...  SaleType SaleCondition SalePrice
0          60       RL         65.0  ...        WD        Normal    208500

[1 rows x 76 columns]

In [ ]:
# checks for missing values columnwise
features_missing=list(data.columns[data.isna().any()])
len(features_missing)

15

In [ ]:
mean_fill,bfill=[],[]

In [ ]:
for feature in features_missing:
  print (feature,'',data[feature].isna().sum()/len(data)*100,' ',data[feature].dtype)
  if data[feature].dtype == 'float64':
    mean_fill.append(feature)
  else:
    bfill.append(feature)

LotFrontage  17.73972602739726   float64
MasVnrType  0.547945205479452   object
MasVnrArea  0.547945205479452   float64
BsmtQual  2.5342465753424657   object
BsmtCond  2.5342465753424657   object
BsmtExposure  2.6027397260273974   object
BsmtFinType1  2.5342465753424657   object
BsmtFinType2  2.6027397260273974   object
Electrical  0.0684931506849315   object
FireplaceQu  47.26027397260274   object
GarageType  5.5479452054794525   object
GarageYrBlt  5.5479452054794525   float64
GarageFinish  5.5479452054794525   object
GarageQual  5.5479452054794525   object
GarageCond  5.5479452054794525   object


In [ ]:
bfill

['MasVnrType',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Electrical',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond']

In [ ]:
for feature in mean_fill:
    data[feature].fillna(data[feature].mean(),inplace=True)

In [ ]:
for feature in bfill:
    data[feature].fillna(method='bfill',inplace=True)

In [ ]:
data['FireplaceQu'].fillna(method='ffill',inplace=True)

# **ENCODE THE DATASET** 

In [ ]:
# construct a list for categorical features
categorical_features=list(data.select_dtypes(include=['object']).columns)
categorical_features

['MSZoning',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinType2',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 'KitchenQual',
 'Functional',
 'FireplaceQu',
 'GarageType',
 'GarageFinish',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'SaleType',
 'SaleCondition']

In [ ]:
# deduce a list of numerical features from the original features excluding categorical features
numerical_list = list(set(original_features)-set(categorical_features))
numerical_list

In [ ]:
norminal=['MSZoning','LandContour','Neighborhood']
ordinal=list(set(categorical_features)-set(norminal))
ordinal

['HeatingQC',
 'BsmtExposure',
 'BldgType',
 'GarageCond',
 'MasVnrType',
 'CentralAir',
 'ExterCond',
 'LandSlope',
 'HouseStyle',
 'BsmtFinType1',
 'Condition1',
 'Heating',
 'GarageType',
 'Condition2',
 'Electrical',
 'FireplaceQu',
 'RoofStyle',
 'SaleType',
 'Exterior2nd',
 'BsmtFinType2',
 'RoofMatl',
 'KitchenQual',
 'Street',
 'Exterior1st',
 'GarageQual',
 'GarageFinish',
 'Utilities',
 'BsmtQual',
 'Foundation',
 'ExterQual',
 'Functional',
 'SaleCondition',
 'LotShape',
 'PavedDrive',
 'BsmtCond',
 'LotConfig']

In [ ]:
target=['SalePrice']

In [ ]:
df_nominal=pd.get_dummies(data[norminal])
df_nominal.head()

MSZoning_C (all)  MSZoning_FV  ...  Neighborhood_Timber  Neighborhood_Veenker
0                 0            0  ...                    0                     0
1                 0            0  ...                    0                     1
2                 0            0  ...                    0                     0
3                 0            0  ...                    0                     0
4                 0            0  ...                    0                     0

[5 rows x 34 columns]

In [ ]:
for feature in ordinal:
  data[feature]=data[feature].astype('category').cat.codes
df_ordinal=data[ordinal]

In [ ]:
df_ordinal

HeatingQC  BsmtExposure  BldgType  ...  PavedDrive  BsmtCond  LotConfig
0             0             3         0  ...           2         3          4
1             0             1         0  ...           2         3          2
2             0             2         0  ...           2         3          4
3             2             3         0  ...           2         1          0
4             0             0         0  ...           2         3          2
...         ...           ...       ...  ...         ...       ...        ...
1455          0             3         0  ...           2         3          4
1456          4             3         0  ...           2         3          4
1457          0             3         0  ...           2         1          4
1458          2             2         0  ...           2         3          4
1459          2             3         0  ...           2         3          4

[1460 rows x 36 columns]

In [ ]:
data[numerical_list]

GarageArea  GarageCars  KitchenAbvGr  ...  OverallQual  FullBath  MiscVal
0            548           2             1  ...            7         2        0
1            460           2             1  ...            6         2        0
2            608           2             1  ...            7         2        0
3            642           3             1  ...            7         1        0
4            836           3             1  ...            8         2        0
...          ...         ...           ...  ...          ...       ...      ...
1455         460           2             1  ...            6         2        0
1456         500           2             1  ...            6         2        0
1457         252           1             1  ...            7         2     2500
1458         240           1             1  ...            5         1        0
1459         276           1             1  ...            5         1        0

[1460 rows x 37 columns]

In [ ]:
new_data=pd.concat([df_nominal,df_nominal,data[numerical_list]],axis=1)

In [ ]:
new_data.shape

(1460, 105)

# **Standardize**

In [ ]:
new_data.drop('SalePrice',axis=1,inplace=True)

In [ ]:
X=new_data.to_numpy()

In [ ]:
X[1]

array([0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 1.000e+00, 4.600e+02, 2.000e+00, 1.000e+00, 0.000e+00,
       0.000e+00, 1.000e+00, 0.000e+00, 2.007e+03, 0.000e+00, 0.000e+00,
       2.000e+01, 8.000e+01, 5.000e+00, 9.780e+02, 

In [ ]:
X=StandardScaler().fit_transform(X)

In [ ]:
X

array([[-0.08304548, -0.21585871, -0.10526316, ...,  0.65147924,
         0.78974052, -0.08768781],
       [-0.08304548, -0.21585871, -0.10526316, ..., -0.07183611,
         0.78974052, -0.08768781],
       [-0.08304548, -0.21585871, -0.10526316, ...,  0.65147924,
         0.78974052, -0.08768781],
       ...,
       [-0.08304548, -0.21585871, -0.10526316, ...,  0.65147924,
         0.78974052,  4.95311151],
       [-0.08304548, -0.21585871, -0.10526316, ..., -0.79515147,
        -1.02604084, -0.08768781],
       [-0.08304548, -0.21585871, -0.10526316, ..., -0.79515147,
        -1.02604084, -0.08768781]])

In [ ]:
data[target]

SalePrice
0        208500
1        181500
2        223500
3        140000
4        250000
...         ...
1455     175000
1456     210000
1457     266500
1458     142125
1459     147500

[1460 rows x 1 columns]

In [ ]:
y=data[target].to_numpy()
y

array([[208500],
       [181500],
       [223500],
       ...,
       [266500],
       [142125],
       [147500]])

In [ ]:
y.shape

(1460, 1)

# **Feature Selection Using L1**

In [ ]:
lsvc = LinearSVC(C=0.02, penalty="l1", dual=False).fit(X, y)
model = SelectFromModel(lsvc, prefit=True)
X_new = model.transform(X)
X_new.shape

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


(1460, 24)

**Spliting the dataset**

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X_new,y,test_size=0.3)

In [ ]:
X_train.shape

(1022, 24)

# **Training the Dataset using Deep Feed Forward ANN**

In [ ]:
epochs=200
model = Sequential()
model.add(Dense(24, activation='relu'))
model.add(Dense(14, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1))

model.compile(Adam(learning_rate=0.01), loss="mse")

history = model.fit(X_train, y_train, validation_split=0.15,batch_size=128, epochs=epochs)

In [ ]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_12 (Dense)             (None, 24)                600       
_________________________________________________________________
dense_13 (Dense)             (None, 14)                350       
_________________________________________________________________
dense_14 (Dense)             (None, 8)                 120       
_________________________________________________________________
dense_15 (Dense)             (None, 1)                 9         
Total params: 1,079
Trainable params: 1,079
Non-trainable params: 0
_________________________________________________________________


# **Testing the Model**

In [ ]:
y_test[10]

array([119000])

In [ ]:
y_predicted=model.predict(X_test)
print(y_predicted[10])


[118517.195]


In [ ]:
print("MSE",metrics.mean_squared_error(y_test,y_predicted))
print("MAE",metrics.mean_absolute_error(y_test,y_predicted))

MSE 2297042551.0245056
MAE 28335.963470319635
